$script:LocalizationCatalog = @{
    'en-US' = @{
        'App.Name' = 'SegoeUI-FontLink-Fixer'
        'Usage.Header' = 'Usage:'
        'Usage.Profiles' = 'Profiles:'
        'Usage.Command.Backup' = '.\SegoeLinker.ps1 backup'
        'Usage.Command.Apply' = '.\SegoeLinker.ps1 apply <profile-id> [--dry-run] [--lang <language-id>]'
        'Usage.Command.RestoreLatest' = '.\SegoeLinker.ps1 restore --latest [--lang <language-id>]'
        'Usage.Command.RestoreFile' = '.\SegoeLinker.ps1 restore --file <backup-directory> [--lang <language-id>]'
        'Usage.Command.List' = '.\SegoeLinker.ps1 list [--lang <language-id>]'
        'Usage.Command.Status' = '.\SegoeLinker.ps1 status [--lang <language-id>]'
        'Usage.Command.Tui' = '.\SegoeLinker.ps1 tui [--lang <language-id>]'
        'Usage.Command.Help' = '.\SegoeLinker.ps1 help'
        'Language.Name.en-US' = 'English'
        'Language.Name.zh-CN' = 'Simplified Chinese'
        'Language.Name.zh-TW' = 'Traditional Chinese'
        'Language.Name.ja-JP' = 'Japanese'
        'Language.Name.ko-KR' = 'Korean'
        'Profile.Name.zh-CN' = 'Simplified Chinese'
        'Profile.Name.zh-TW' = 'Traditional Chinese'
        'Profile.Name.ja-JP' = 'Japanese'
        'Profile.Name.ko-KR' = 'Korean'
        'Profile.Description.zh-CN' = 'Prefer Microsoft YaHei fonts earlier in Segoe UI fallback lists.'
        'Profile.Description.zh-TW' = 'Prefer Microsoft JhengHei fonts earlier in Segoe UI fallback lists.'
        'Profile.Description.ja-JP' = 'Prefer Yu Gothic UI and Meiryo fonts earlier in Segoe UI fallback lists.'
        'Profile.Description.ko-KR' = 'Prefer Malgun Gothic earlier in Segoe UI fallback lists.'
        'State.Admin' = 'administrator'
        'State.StandardUser' = 'standard user'
        'State.RunningAsAdmin' = 'running as administrator.'
        'State.RunningWithoutAdmin' = 'running without administrator rights.'
        'Elevation.NotAdmin' = 'Elevation state: not running as administrator.'
        'Elevation.Relaunching' = 'Relaunching the command with elevation before any registry writes occur.'
        'Error.StartElevated' = 'Failed to start the elevated PowerShell process.'
        'Error.ApplyMissingProfile' = 'The apply command requires a profile id such as zh-CN or ja-JP.'
        'Error.UnknownApplyOption' = 'Unknown apply option: {0}'
        'Error.LanguageIdRequired' = 'The --lang option requires a language id.'
        'Error.RestoreMissingPath' = 'The restore --file option requires a backup directory path.'
        'Error.UnknownRestoreOption' = 'Unknown restore option: {0}'
        'Error.UnknownGlobalOption' = 'Unknown global option: {0}'
        'Error.UnknownCommand' = 'Unknown command: {0}'
        'Error.UnsupportedProfile' = 'Unsupported profile "{0}". Supported profiles: {1}.'
        'Error.RegistryKeyNotFound' = 'Registry key not found: {0}'
        'Error.UnsupportedSnapshotKind' = 'Unsupported registry value kind in snapshot: {0}'
        'Error.NoSegoeValues' = 'No registry values starting with "Segoe UI" were found under the SystemLink key.'
        'Error.NoManagedValues' = 'No managed registry values were found under the SystemLink key for this profile.'
        'Error.NonMultiString' = 'Registry value "{0}" is "{1}", but this tool only supports MultiString FontLink values.'
        'Error.ApplyVerificationMissing' = 'Verification failed: missing value after apply: {0}'
        'Error.ApplyVerificationMismatch' = 'Verification failed: written value does not match expectation: {0}'
        'Error.ApplyVerificationFailed' = 'Apply verification failed. Use the backup at "{0}" if you need to restore the previous state.'
        'Error.RestoreLatestOrFile' = 'Use either --latest or --file, not both.'
        'Error.RestoreSelectorRequired' = 'Restore requires either --latest or --file <path>.'
        'Error.NoValidBackups' = 'No valid backups were found in {0}.'
        'Error.BackupDirectoryExists' = 'Refusing to overwrite existing backup directory: {0}'
        'Error.BackupManifestNotFound' = 'Backup manifest not found: {0}'
        'Error.BackupIncompleteDirectory' = 'Backup directory is marked incomplete and cannot be used: {0}'
        'Error.BackupManifestIncomplete' = 'Backup manifest is not complete: {0}'
        'Error.UnsupportedBackupSchema' = 'Unsupported backup schema version "{0}" in {1}.'
        'Error.BackupWrongRegistryKey' = 'Backup manifest targets a different registry key: {0}'
        'Error.BackupFileMissing' = 'Backup file is missing: {0}'
        'Error.BackupSnapshotHashMismatch' = 'Snapshot hash mismatch for backup: {0}'
        'Error.BackupRegHashMismatch' = 'Registry export hash mismatch for backup: {0}'
        'Error.BackupSnapshotWrongPath' = 'Backup snapshot targets a different registry path: {0}'
        'Error.RegistryExportExists' = 'Refusing to overwrite existing registry export: {0}'
        'Error.RegistryExportFailed' = 'Registry export failed: {0}'
        'Error.RestoreVerificationFailed' = 'Restore verification failed. The pre-restore safety backup is available at "{0}".'
        'Error.InvalidSelection' = 'Invalid selection. Please try again.'
        'Error.InvalidLanguage' = 'Unsupported language "{0}". Supported languages: {1}.'
        'Error.ChildCommandFailed' = 'The command exited with code {0}.'
        'Header.Backup' = 'Backup'
        'Header.Apply' = 'Apply Changes'
        'Header.Restore' = 'Restore'
        'Header.Status' = 'Status'
        'Header.Profiles' = 'Supported Profiles'
        'Header.Preview' = 'Preview For {0}'
        'Header.Tui' = 'Main Menu'
        'Info.ElevationState' = 'Elevation state: {0}'
        'Info.BackingUpKey' = 'Backing up entire registry key: {0}'
        'Info.BackupCompleted' = 'Backup completed: {0}'
        'Info.RegistryExport' = 'Registry export: {0}'
        'Info.SnapshotJson' = 'Snapshot JSON: {0}'
        'Info.ProfileTargetFonts' = 'Profile target fonts: {0}'
        'Info.MatchingSegoeValues' = 'Matching "Segoe UI*" values found: {0}'
        'Info.ManagedValuesFound' = 'Matching managed values found: {0}'
        'Info.DryRunNoWrite' = 'Dry-run mode: no registry writes were performed.'
        'Info.BackupLocation' = 'Backup location: {0}'
        'Info.UpdatingValue' = 'Updating {0}'
        'Info.RegistryPath' = 'Registry path: {0}'
        'Info.LatestValidBackup' = 'Latest valid backup: {0}'
        'Info.TotalSystemLinkValues' = 'Total SystemLink values: {0}'
        'Info.SelectedBackup' = 'Selected backup: {0}'
        'Info.CreatedAtUtc' = 'Created at UTC: {0}'
        'Info.ContainsValues' = 'Contains {0} registry value(s).'
        'Info.ValueNamesToRestore' = 'Value names that will be restored:'
        'Info.CurrentStateSafetyBackup' = 'Current state safety backup: {0}'
        'Info.LanguageSwitched' = 'Interface language switched to {0}.'
        'Info.CurrentLanguage' = 'Current language: {0}'
        'Info.LatestBackupSummaryNone' = 'none'
        'Success.NoChangesNeeded' = 'Nothing needed to change, so no backup or registry write was performed.'
        'Success.NoOrderingChanges' = 'No ordering changes are needed for this profile.'
        'Success.ApplyVerified' = 'Verified {0} updated managed value(s).'
        'Success.RestoreVerified' = 'Restore verified successfully from backup {0}.'
        'Warn.LogoffRequired' = 'Windows may require logoff, reboot, or application restart before FontLink changes fully take effect.'
        'Warn.NoSegoeValuesPreview' = 'No registry values starting with "Segoe UI" were found under the target key.'
        'Warn.NoManagedValuesPreview' = 'No managed registry values were found under the target key for this profile.'
        'Preview.Value' = 'Value: {0}'
        'Preview.WillChange' = 'Will change: {0}'
        'Preview.Yes' = 'Yes'
        'Preview.No' = 'No'
        'Preview.Before' = 'Before:'
        'Preview.After' = 'After:'
        'Label.Profile' = 'Profile: {0}'
        'Label.Name' = '  Name: {0}'
        'Label.Description' = '  Description: {0}'
        'Label.PriorityFonts' = '  Priority fonts: {0}'
        'Tui.Welcome' = 'Single-key main menu.'
        'Tui.Option.Backup' = '1. Backup current SystemLink key'
        'Tui.Option.PreviewApply' = '2. Preview profile changes'
        'Tui.Option.Apply' = '3. Apply a profile'
        'Tui.Option.RestoreLatest' = '4. Restore latest valid backup'
        'Tui.Option.RestorePath' = '5. Restore from a specific backup path'
        'Tui.Option.Status' = '6. Show current status'
        'Tui.Option.ListProfiles' = '7. List supported profiles'
        'Tui.Option.SwitchLanguage' = '8. Switch interface language'
        'Tui.Option.Help' = '9. Show command help'
        'Tui.Option.Exit' = '0. Exit'
        'Tui.Option.Back' = '0. Back'
        'Tui.Option.Confirm' = '1. Confirm'
        'Tui.Option.Cancel' = '0. Cancel'
        'Tui.ActionHint' = 'Number key: open'
        'Tui.PressAnyKey' = 'Any key: return'
        'Tui.Prompt.SelectOption' = 'Select an option'
        'Tui.Prompt.SelectProfile' = 'Enter a profile id'
        'Tui.Prompt.BackupPath' = 'Enter a backup directory or manifest path'
        'Tui.Prompt.SelectLanguage' = 'Enter a language id'
        'Tui.Prompt.PressEnter' = 'Press Enter to continue'
        'Tui.Prompt.ConfirmApply' = 'Apply the selected profile now?'
        'Tui.Prompt.ConfirmRestoreLatest' = 'Restore the latest valid backup now?'
        'Tui.Prompt.ConfirmRestorePath' = 'Restore from the entered backup path now?'
        'Tui.LanguagesHeader' = 'Available interface languages:'
        'Tui.Header.SelectProfile' = 'Select Profile'
        'Tui.Header.SelectLanguage' = 'Select Interface Language'
        'Tui.Header.Confirm' = 'Confirm Action'
        'Tui.Cancelled' = 'Cancelled.'
    };
    'zh-CN' = @{
        'App.Name' = 'SegoeUI-FontLink-Fixer'
        'Usage.Header' = '用法：'
        'Usage.Profiles' = '支持的配置：'
        'Usage.Command.Backup' = '.\SegoeLinker.ps1 backup'
        'Usage.Command.Apply' = '.\SegoeLinker.ps1 apply <profile-id> [--dry-run] [--lang <language-id>]'
        'Usage.Command.RestoreLatest' = '.\SegoeLinker.ps1 restore --latest [--lang <language-id>]'
        'Usage.Command.RestoreFile' = '.\SegoeLinker.ps1 restore --file <backup-directory> [--lang <language-id>]'
        'Usage.Command.List' = '.\SegoeLinker.ps1 list [--lang <language-id>]'
        'Usage.Command.Status' = '.\SegoeLinker.ps1 status [--lang <language-id>]'
        'Usage.Command.Tui' = '.\SegoeLinker.ps1 tui [--lang <language-id>]'
        'Usage.Command.Help' = '.\SegoeLinker.ps1 help'
        'Language.Name.en-US' = 'English'
        'Language.Name.zh-CN' = '简体中文'
        'Language.Name.zh-TW' = '繁體中文'
        'Language.Name.ja-JP' = '日本語'
        'Language.Name.ko-KR' = '한국어'
        'Profile.Name.zh-CN' = '简体中文'
        'Profile.Name.zh-TW' = '繁體中文'
        'Profile.Name.ja-JP' = '日语'
        'Profile.Name.ko-KR' = '韩语'
        'Profile.Description.zh-CN' = '将 Microsoft YaHei 系列字体优先前移。'
        'Profile.Description.zh-TW' = '将 Microsoft JhengHei 系列字体优先前移。'
        'Profile.Description.ja-JP' = '将 Yu Gothic UI 与 Meiryo 系列字体优先前移。'
        'Profile.Description.ko-KR' = '将 Malgun Gothic 系列字体优先前移。'
        'State.Admin' = '管理员'
        'State.StandardUser' = '标准用户'
        'State.RunningAsAdmin' = '当前以管理员身份运行。'
        'State.RunningWithoutAdmin' = '当前未以管理员身份运行。'
        'Elevation.NotAdmin' = '提权状态：当前不是管理员会话。'
        'Elevation.Relaunching' = '在发生任何注册表写入之前，将以管理员权限重新启动此命令。'
        'Error.StartElevated' = '启动提升权限后的 PowerShell 进程失败。'
        'Error.ApplyMissingProfile' = 'apply 命令需要提供配置 ID，例如 zh-CN 或 ja-JP。'
        'Error.UnknownApplyOption' = '未知的 apply 选项：{0}'
        'Error.LanguageIdRequired' = '--lang 选项需要提供语言 ID。'
        'Error.RestoreMissingPath' = 'restore --file 选项需要一个备份目录路径。'
        'Error.UnknownRestoreOption' = '未知的 restore 选项：{0}'
        'Error.UnknownGlobalOption' = '未知的全局选项：{0}'
        'Error.UnknownCommand' = '未知命令：{0}'
        'Error.UnsupportedProfile' = '不支持的配置 "{0}"。支持的配置有：{1}。'
        'Error.RegistryKeyNotFound' = '找不到注册表键：{0}'
        'Error.UnsupportedSnapshotKind' = '快照中包含不支持的注册表值类型：{0}'
        'Error.NoSegoeValues' = '在 SystemLink 键下没有找到任何以 "Segoe UI" 开头的注册表值。'
        'Error.NoManagedValues' = '在 SystemLink 键下没有找到此配置要管理的注册表值。'
        'Error.NonMultiString' = '注册表值 "{0}" 的类型是 "{1}"，本工具只支持 MultiString 类型的 FontLink 值。'
        'Error.ApplyVerificationMissing' = '校验失败：应用后缺少注册表值：{0}'
        'Error.ApplyVerificationMismatch' = '校验失败：写入后的值与预期不一致：{0}'
        'Error.ApplyVerificationFailed' = '应用后的校验失败。如需恢复之前的状态，请使用备份："{0}"。'
        'Error.RestoreLatestOrFile' = '请只使用 --latest 或 --file 其中之一，不要同时使用。'
        'Error.RestoreSelectorRequired' = 'restore 必须指定 --latest 或 --file <path>。'
        'Error.NoValidBackups' = '在 {0} 中没有找到有效备份。'
        'Error.BackupDirectoryExists' = '拒绝覆盖已有备份目录：{0}'
        'Error.BackupManifestNotFound' = '找不到备份清单：{0}'
        'Error.BackupIncompleteDirectory' = '该备份目录被标记为不完整，不能用于恢复：{0}'
        'Error.BackupManifestIncomplete' = '备份清单不完整：{0}'
        'Error.UnsupportedBackupSchema' = '备份清单 {1} 使用了不支持的 schema 版本 "{0}"。'
        'Error.BackupWrongRegistryKey' = '备份清单对应的注册表目标不正确：{0}'
        'Error.BackupFileMissing' = '备份文件缺失：{0}'
        'Error.BackupSnapshotHashMismatch' = '备份快照哈希不匹配：{0}'
        'Error.BackupRegHashMismatch' = '备份 reg 导出文件哈希不匹配：{0}'
        'Error.BackupSnapshotWrongPath' = '备份快照对应的注册表路径不正确：{0}'
        'Error.RegistryExportExists' = '拒绝覆盖已有的注册表导出文件：{0}'
        'Error.RegistryExportFailed' = '注册表导出失败：{0}'
        'Error.RestoreVerificationFailed' = '恢复后的校验失败。恢复前的安全备份位于："{0}"。'
        'Error.InvalidSelection' = '无效的选择，请重试。'
        'Error.InvalidLanguage' = '不支持的界面语言 "{0}"。支持的语言有：{1}。'
        'Error.ChildCommandFailed' = '命令执行结束，退出码为 {0}。'
        'Header.Backup' = '备份'
        'Header.Apply' = '应用变更'
        'Header.Restore' = '恢复'
        'Header.Status' = '状态'
        'Header.Profiles' = '支持的配置'
        'Header.Preview' = '{0} 预览'
        'Header.Tui' = '主菜单'
        'Info.ElevationState' = '提权状态：{0}'
        'Info.BackingUpKey' = '正在备份整个注册表键：{0}'
        'Info.BackupCompleted' = '备份完成：{0}'
        'Info.RegistryExport' = '注册表导出：{0}'
        'Info.SnapshotJson' = 'JSON 快照：{0}'
        'Info.ProfileTargetFonts' = '配置优先字体：{0}'
        'Info.MatchingSegoeValues' = '找到匹配的 "Segoe UI*" 值数量：{0}'
        'Info.ManagedValuesFound' = '找到受此配置管理的注册表值数量：{0}'
        'Info.DryRunNoWrite' = '当前是 dry-run 模式：不会写入注册表。'
        'Info.BackupLocation' = '备份位置：{0}'
        'Info.UpdatingValue' = '正在更新 {0}'
        'Info.RegistryPath' = '注册表路径：{0}'
        'Info.LatestValidBackup' = '最近的有效备份：{0}'
        'Info.TotalSystemLinkValues' = 'SystemLink 中的值总数：{0}'
        'Info.SelectedBackup' = '已选择的备份：{0}'
        'Info.CreatedAtUtc' = '创建时间（UTC）：{0}'
        'Info.ContainsValues' = '包含 {0} 个注册表值。'
        'Info.ValueNamesToRestore' = '即将恢复的注册表值名称：'
        'Info.CurrentStateSafetyBackup' = '当前状态安全备份：{0}'
        'Info.LanguageSwitched' = '界面语言已切换为：{0}'
        'Info.CurrentLanguage' = '当前界面语言：{0}'
        'Info.LatestBackupSummaryNone' = '无'
        'Success.NoChangesNeeded' = '当前无需变更，因此不会创建备份，也不会写入注册表。'
        'Success.NoOrderingChanges' = '此配置当前不需要调整顺序。'
        'Success.ApplyVerified' = '已校验并成功更新 {0} 个受管理的注册表值。'
        'Success.RestoreVerified' = '已成功从备份 {0} 恢复并完成校验。'
        'Warn.LogoffRequired' = 'FontLink 变更可能需要注销、重启，或重启相关应用后才会完全生效。'
        'Warn.NoSegoeValuesPreview' = '目标注册表键下没有找到任何以 "Segoe UI" 开头的值。'
        'Warn.NoManagedValuesPreview' = '目标注册表键下没有找到此配置要管理的注册表值。'
        'Preview.Value' = '注册表值：{0}'
        'Preview.WillChange' = '是否会变更：{0}'
        'Preview.Yes' = '是'
        'Preview.No' = '否'
        'Preview.Before' = '变更前：'
        'Preview.After' = '变更后：'
        'Label.Profile' = '配置：{0}'
        'Label.Name' = '  名称：{0}'
        'Label.Description' = '  说明：{0}'
        'Label.PriorityFonts' = '  优先字体：{0}'
        'Tui.Welcome' = '单键主菜单'
        'Tui.Option.Backup' = '1. 备份当前 SystemLink 键'
        'Tui.Option.PreviewApply' = '2. 预览配置变更'
        'Tui.Option.Apply' = '3. 应用某个配置'
        'Tui.Option.RestoreLatest' = '4. 恢复最近的有效备份'
        'Tui.Option.RestorePath' = '5. 从指定备份路径恢复'
        'Tui.Option.Status' = '6. 查看当前状态'
        'Tui.Option.ListProfiles' = '7. 列出支持的配置'
        'Tui.Option.SwitchLanguage' = '8. 切换界面语言'
        'Tui.Option.Help' = '9. 显示命令帮助'
        'Tui.Option.Exit' = '0. 退出'
        'Tui.Option.Back' = '0. 返回'
        'Tui.Option.Confirm' = '1. 确认'
        'Tui.Option.Cancel' = '0. 取消'
        'Tui.ActionHint' = '数字键：打开功能'
        'Tui.PressAnyKey' = '任意键：返回'
        'Tui.Prompt.SelectOption' = '请输入菜单编号'
        'Tui.Prompt.SelectProfile' = '请输入配置 ID'
        'Tui.Prompt.BackupPath' = '请输入备份目录或 manifest 路径'
        'Tui.Prompt.SelectLanguage' = '请输入语言 ID'
        'Tui.Prompt.PressEnter' = '按 Enter 键继续'
        'Tui.Prompt.ConfirmApply' = '现在应用所选配置吗？'
        'Tui.Prompt.ConfirmRestoreLatest' = '现在恢复最近的有效备份吗？'
        'Tui.Prompt.ConfirmRestorePath' = '现在从刚输入的备份路径恢复吗？'
        'Tui.LanguagesHeader' = '可用界面语言：'
        'Tui.Header.SelectProfile' = '选择配置'
        'Tui.Header.SelectLanguage' = '选择界面语言'
        'Tui.Header.Confirm' = '确认操作'
        'Tui.Cancelled' = '已取消。'
    };
    'zh-TW' = @{
        'App.Name' = 'SegoeUI-FontLink-Fixer'
        'Usage.Header' = '用法：'
        'Usage.Profiles' = '支援的設定：'
        'Usage.Command.Backup' = '.\SegoeLinker.ps1 backup'
        'Usage.Command.Apply' = '.\SegoeLinker.ps1 apply <profile-id> [--dry-run] [--lang <language-id>]'
        'Usage.Command.RestoreLatest' = '.\SegoeLinker.ps1 restore --latest [--lang <language-id>]'
        'Usage.Command.RestoreFile' = '.\SegoeLinker.ps1 restore --file <backup-directory> [--lang <language-id>]'
        'Usage.Command.List' = '.\SegoeLinker.ps1 list [--lang <language-id>]'
        'Usage.Command.Status' = '.\SegoeLinker.ps1 status [--lang <language-id>]'
        'Usage.Command.Tui' = '.\SegoeLinker.ps1 tui [--lang <language-id>]'
        'Usage.Command.Help' = '.\SegoeLinker.ps1 help'
        'Language.Name.en-US' = 'English'
        'Language.Name.zh-CN' = '简体中文'
        'Language.Name.zh-TW' = '繁體中文'
        'Language.Name.ja-JP' = '日本語'
        'Language.Name.ko-KR' = '한국어'
        'Profile.Name.zh-CN' = '簡體中文'
        'Profile.Name.zh-TW' = '繁體中文'
        'Profile.Name.ja-JP' = '日文'
        'Profile.Name.ko-KR' = '韓文'
        'Profile.Description.zh-CN' = '優先提前 Microsoft YaHei 系列字型。'
        'Profile.Description.zh-TW' = '優先提前 Microsoft JhengHei 系列字型。'
        'Profile.Description.ja-JP' = '優先提前 Yu Gothic UI 與 Meiryo 系列字型。'
        'Profile.Description.ko-KR' = '優先提前 Malgun Gothic 系列字型。'
        'State.Admin' = '系統管理員'
        'State.StandardUser' = '一般使用者'
        'State.RunningAsAdmin' = '目前以系統管理員身分執行。'
        'State.RunningWithoutAdmin' = '目前未以系統管理員身分執行。'
        'Elevation.NotAdmin' = '權限狀態：目前不是系統管理員工作階段。'
        'Elevation.Relaunching' = '在進行任何登錄寫入之前，將以系統管理員權限重新啟動此命令。'
        'Error.StartElevated' = '啟動提升權限後的 PowerShell 行程失敗。'
        'Error.ApplyMissingProfile' = 'apply 命令需要提供設定 ID，例如 zh-CN 或 ja-JP。'
        'Error.UnknownApplyOption' = '未知的 apply 選項：{0}'
        'Error.LanguageIdRequired' = '--lang 選項需要提供語言 ID。'
        'Error.RestoreMissingPath' = 'restore --file 選項需要一個備份目錄路徑。'
        'Error.UnknownRestoreOption' = '未知的 restore 選項：{0}'
        'Error.UnknownGlobalOption' = '未知的全域選項：{0}'
        'Error.UnknownCommand' = '未知命令：{0}'
        'Error.UnsupportedProfile' = '不支援的設定 "{0}"。支援的設定有：{1}。'
        'Error.RegistryKeyNotFound' = '找不到登錄機碼：{0}'
        'Error.UnsupportedSnapshotKind' = '快照中包含不支援的登錄值類型：{0}'
        'Error.NoSegoeValues' = '在 SystemLink 機碼下找不到任何以 "Segoe UI" 開頭的登錄值。'
        'Error.NoManagedValues' = '在 SystemLink 機碼下找不到此設定要管理的登錄值。'
        'Error.NonMultiString' = '登錄值 "{0}" 的類型為 "{1}"，本工具只支援 MultiString 類型的 FontLink 值。'
        'Error.ApplyVerificationMissing' = '驗證失敗：套用後缺少登錄值：{0}'
        'Error.ApplyVerificationMismatch' = '驗證失敗：寫入後的值與預期不一致：{0}'
        'Error.ApplyVerificationFailed' = '套用後驗證失敗。如需還原先前狀態，請使用備份："{0}"。'
        'Error.RestoreLatestOrFile' = '請只使用 --latest 或 --file 其中之一，不要同時使用。'
        'Error.RestoreSelectorRequired' = 'restore 必須指定 --latest 或 --file <path>。'
        'Error.NoValidBackups' = '在 {0} 中找不到有效備份。'
        'Error.BackupDirectoryExists' = '拒絕覆寫既有備份目錄：{0}'
        'Error.BackupManifestNotFound' = '找不到備份資訊清單：{0}'
        'Error.BackupIncompleteDirectory' = '此備份目錄被標記為不完整，無法用於還原：{0}'
        'Error.BackupManifestIncomplete' = '備份資訊清單不完整：{0}'
        'Error.UnsupportedBackupSchema' = '備份資訊清單 {1} 使用了不支援的 schema 版本 "{0}"。'
        'Error.BackupWrongRegistryKey' = '備份資訊清單對應的登錄目標不正確：{0}'
        'Error.BackupFileMissing' = '缺少備份檔案：{0}'
        'Error.BackupSnapshotHashMismatch' = '備份快照雜湊不符：{0}'
        'Error.BackupRegHashMismatch' = '備份 reg 匯出檔雜湊不符：{0}'
        'Error.BackupSnapshotWrongPath' = '備份快照對應的登錄路徑不正確：{0}'
        'Error.RegistryExportExists' = '拒絕覆寫既有登錄匯出檔：{0}'
        'Error.RegistryExportFailed' = '登錄匯出失敗：{0}'
        'Error.RestoreVerificationFailed' = '還原後驗證失敗。還原前的安全備份位於："{0}"。'
        'Error.InvalidSelection' = '無效的選擇，請重試。'
        'Error.InvalidLanguage' = '不支援的介面語言 "{0}"。支援的語言有：{1}。'
        'Error.ChildCommandFailed' = '命令已結束，退出碼為 {0}。'
        'Header.Backup' = '備份'
        'Header.Apply' = '套用變更'
        'Header.Restore' = '還原'
        'Header.Status' = '狀態'
        'Header.Profiles' = '支援的設定'
        'Header.Preview' = '{0} 預覽'
        'Header.Tui' = '主選單'
        'Info.ElevationState' = '權限狀態：{0}'
        'Info.BackingUpKey' = '正在備份整個登錄機碼：{0}'
        'Info.BackupCompleted' = '備份完成：{0}'
        'Info.RegistryExport' = '登錄匯出：{0}'
        'Info.SnapshotJson' = 'JSON 快照：{0}'
        'Info.ProfileTargetFonts' = '設定優先字型：{0}'
        'Info.MatchingSegoeValues' = '找到符合的 "Segoe UI*" 值數量：{0}'
        'Info.ManagedValuesFound' = '找到此設定管理的登錄值數量：{0}'
        'Info.DryRunNoWrite' = '目前為 dry-run 模式：不會寫入登錄。'
        'Info.BackupLocation' = '備份位置：{0}'
        'Info.UpdatingValue' = '正在更新 {0}'
        'Info.RegistryPath' = '登錄路徑：{0}'
        'Info.LatestValidBackup' = '最近的有效備份：{0}'
        'Info.TotalSystemLinkValues' = 'SystemLink 中的值總數：{0}'
        'Info.SelectedBackup' = '已選取的備份：{0}'
        'Info.CreatedAtUtc' = '建立時間（UTC）：{0}'
        'Info.ContainsValues' = '包含 {0} 個登錄值。'
        'Info.ValueNamesToRestore' = '即將還原的登錄值名稱：'
        'Info.CurrentStateSafetyBackup' = '目前狀態安全備份：{0}'
        'Info.LanguageSwitched' = '介面語言已切換為：{0}'
        'Info.CurrentLanguage' = '目前介面語言：{0}'
        'Info.LatestBackupSummaryNone' = '無'
        'Success.NoChangesNeeded' = '目前不需要變更，因此不會建立備份，也不會寫入登錄。'
        'Success.NoOrderingChanges' = '此設定目前不需要調整順序。'
        'Success.ApplyVerified' = '已驗證並成功更新 {0} 個受管理的登錄值。'
        'Success.RestoreVerified' = '已成功從備份 {0} 還原並完成驗證。'
        'Warn.LogoffRequired' = 'FontLink 變更可能需要登出、重新開機，或重新啟動相關應用程式後才會完全生效。'
        'Warn.NoSegoeValuesPreview' = '目標登錄機碼下找不到任何以 "Segoe UI" 開頭的值。'
        'Warn.NoManagedValuesPreview' = '目標登錄機碼下找不到此設定要管理的登錄值。'
        'Preview.Value' = '登錄值：{0}'
        'Preview.WillChange' = '是否會變更：{0}'
        'Preview.Yes' = '是'
        'Preview.No' = '否'
        'Preview.Before' = '變更前：'
        'Preview.After' = '變更後：'
        'Label.Profile' = '設定：{0}'
        'Label.Name' = '  名稱：{0}'
        'Label.Description' = '  說明：{0}'
        'Label.PriorityFonts' = '  優先字型：{0}'
        'Tui.Welcome' = '單鍵主選單'
        'Tui.Option.Backup' = '1. 備份目前的 SystemLink 機碼'
        'Tui.Option.PreviewApply' = '2. 預覽設定變更'
        'Tui.Option.Apply' = '3. 套用某個設定'
        'Tui.Option.RestoreLatest' = '4. 還原最近的有效備份'
        'Tui.Option.RestorePath' = '5. 從指定備份路徑還原'
        'Tui.Option.Status' = '6. 查看目前狀態'
        'Tui.Option.ListProfiles' = '7. 列出支援的設定'
        'Tui.Option.SwitchLanguage' = '8. 切換介面語言'
        'Tui.Option.Help' = '9. 顯示命令說明'
        'Tui.Option.Exit' = '0. 離開'
        'Tui.Option.Back' = '0. 返回'
        'Tui.Option.Confirm' = '1. 確認'
        'Tui.Option.Cancel' = '0. 取消'
        'Tui.ActionHint' = '數字鍵：開啟功能'
        'Tui.PressAnyKey' = '任意鍵：返回'
        'Tui.Prompt.SelectOption' = '請輸入選單編號'
        'Tui.Prompt.SelectProfile' = '請輸入設定 ID'
        'Tui.Prompt.BackupPath' = '請輸入備份目錄或 manifest 路徑'
        'Tui.Prompt.SelectLanguage' = '請輸入語言 ID'
        'Tui.Prompt.PressEnter' = '按 Enter 繼續'
        'Tui.Prompt.ConfirmApply' = '現在要套用所選設定嗎？'
        'Tui.Prompt.ConfirmRestoreLatest' = '現在要還原最近的有效備份嗎？'
        'Tui.Prompt.ConfirmRestorePath' = '現在要從剛輸入的備份路徑還原嗎？'
        'Tui.LanguagesHeader' = '可用介面語言：'
        'Tui.Header.SelectProfile' = '選擇設定'
        'Tui.Header.SelectLanguage' = '選擇介面語言'
        'Tui.Header.Confirm' = '確認操作'
        'Tui.Cancelled' = '已取消。'
    };
    'ja-JP' = @{
        'App.Name' = 'SegoeUI-FontLink-Fixer'
        'Usage.Header' = '使い方:'
        'Usage.Profiles' = '対応プロファイル:'
        'Usage.Command.Backup' = '.\SegoeLinker.ps1 backup'
        'Usage.Command.Apply' = '.\SegoeLinker.ps1 apply <profile-id> [--dry-run] [--lang <language-id>]'
        'Usage.Command.RestoreLatest' = '.\SegoeLinker.ps1 restore --latest [--lang <language-id>]'
        'Usage.Command.RestoreFile' = '.\SegoeLinker.ps1 restore --file <backup-directory> [--lang <language-id>]'
        'Usage.Command.List' = '.\SegoeLinker.ps1 list [--lang <language-id>]'
        'Usage.Command.Status' = '.\SegoeLinker.ps1 status [--lang <language-id>]'
        'Usage.Command.Tui' = '.\SegoeLinker.ps1 tui [--lang <language-id>]'
        'Usage.Command.Help' = '.\SegoeLinker.ps1 help'
        'Language.Name.en-US' = 'English'
        'Language.Name.zh-CN' = '简体中文'
        'Language.Name.zh-TW' = '繁體中文'
        'Language.Name.ja-JP' = '日本語'
        'Language.Name.ko-KR' = '한국어'
        'Profile.Name.zh-CN' = '簡体字中国語'
        'Profile.Name.zh-TW' = '繁体字中国語'
        'Profile.Name.ja-JP' = '日本語'
        'Profile.Name.ko-KR' = '韓国語'
        'Profile.Description.zh-CN' = 'Microsoft YaHei 系フォントをより前に移動します。'
        'Profile.Description.zh-TW' = 'Microsoft JhengHei 系フォントをより前に移動します。'
        'Profile.Description.ja-JP' = 'Yu Gothic UI と Meiryo 系フォントをより前に移動します。'
        'Profile.Description.ko-KR' = 'Malgun Gothic 系フォントをより前に移動します。'
        'State.Admin' = '管理者'
        'State.StandardUser' = '標準ユーザー'
        'State.RunningAsAdmin' = '現在は管理者として実行中です。'
        'State.RunningWithoutAdmin' = '現在は管理者権限なしで実行中です。'
        'Elevation.NotAdmin' = '昇格状態: 現在のセッションは管理者ではありません。'
        'Elevation.Relaunching' = 'レジストリ書き込みを行う前に、管理者権限でコマンドを再起動します。'
        'Error.StartElevated' = '昇格後の PowerShell プロセスの起動に失敗しました。'
        'Error.ApplyMissingProfile' = 'apply コマンドには zh-CN や ja-JP などのプロファイル ID が必要です。'
        'Error.UnknownApplyOption' = '不明な apply オプションです: {0}'
        'Error.LanguageIdRequired' = '--lang オプションには言語 ID が必要です。'
        'Error.RestoreMissingPath' = 'restore --file オプションにはバックアップディレクトリのパスが必要です。'
        'Error.UnknownRestoreOption' = '不明な restore オプションです: {0}'
        'Error.UnknownGlobalOption' = '不明なグローバルオプションです: {0}'
        'Error.UnknownCommand' = '不明なコマンドです: {0}'
        'Error.UnsupportedProfile' = '未対応のプロファイル "{0}" です。対応プロファイル: {1}。'
        'Error.RegistryKeyNotFound' = 'レジストリ キーが見つかりません: {0}'
        'Error.UnsupportedSnapshotKind' = 'スナップショット内に未対応のレジストリ値種別があります: {0}'
        'Error.NoSegoeValues' = 'SystemLink キー配下に "Segoe UI" で始まるレジストリ値が見つかりません。'
        'Error.NoManagedValues' = 'SystemLink キー配下に、このプロファイルが管理するレジストリ値が見つかりません。'
        'Error.NonMultiString' = 'レジストリ値 "{0}" の型は "{1}" です。このツールは MultiString 型の FontLink 値のみ対応します。'
        'Error.ApplyVerificationMissing' = '検証失敗: 適用後にレジストリ値が見つかりません: {0}'
        'Error.ApplyVerificationMismatch' = '検証失敗: 書き込まれた値が期待値と一致しません: {0}'
        'Error.ApplyVerificationFailed' = '適用後の検証に失敗しました。元の状態へ戻すにはバックアップ "{0}" を使用してください。'
        'Error.RestoreLatestOrFile' = '--latest と --file は同時に指定できません。どちらか一方のみ使用してください。'
        'Error.RestoreSelectorRequired' = 'restore では --latest または --file <path> のいずれかが必要です。'
        'Error.NoValidBackups' = '{0} に有効なバックアップが見つかりません。'
        'Error.BackupDirectoryExists' = '既存のバックアップ ディレクトリは上書きしません: {0}'
        'Error.BackupManifestNotFound' = 'バックアップ マニフェストが見つかりません: {0}'
        'Error.BackupIncompleteDirectory' = 'このバックアップ ディレクトリは不完全としてマークされているため、復元に使えません: {0}'
        'Error.BackupManifestIncomplete' = 'バックアップ マニフェストが不完全です: {0}'
        'Error.UnsupportedBackupSchema' = 'バックアップ マニフェスト {1} の schema バージョン "{0}" は未対応です。'
        'Error.BackupWrongRegistryKey' = 'バックアップ マニフェストの対象レジストリ キーが一致しません: {0}'
        'Error.BackupFileMissing' = 'バックアップ ファイルが不足しています: {0}'
        'Error.BackupSnapshotHashMismatch' = 'バックアップ スナップショットのハッシュが一致しません: {0}'
        'Error.BackupRegHashMismatch' = 'バックアップ reg エクスポートのハッシュが一致しません: {0}'
        'Error.BackupSnapshotWrongPath' = 'バックアップ スナップショットのレジストリ パスが一致しません: {0}'
        'Error.RegistryExportExists' = '既存のレジストリ エクスポートは上書きしません: {0}'
        'Error.RegistryExportFailed' = 'レジストリのエクスポートに失敗しました: {0}'
        'Error.RestoreVerificationFailed' = '復元後の検証に失敗しました。復元前の安全バックアップは "{0}" にあります。'
        'Error.InvalidSelection' = '無効な選択です。もう一度入力してください。'
        'Error.InvalidLanguage' = '未対応の UI 言語 "{0}" です。対応言語: {1}。'
        'Error.ChildCommandFailed' = 'コマンドは終了コード {0} で終了しました。'
        'Header.Backup' = 'バックアップ'
        'Header.Apply' = '変更の適用'
        'Header.Restore' = '復元'
        'Header.Status' = '状態'
        'Header.Profiles' = '対応プロファイル'
        'Header.Preview' = '{0} のプレビュー'
        'Header.Tui' = 'メインメニュー'
        'Info.ElevationState' = '昇格状態: {0}'
        'Info.BackingUpKey' = 'レジストリ キー全体をバックアップしています: {0}'
        'Info.BackupCompleted' = 'バックアップ完了: {0}'
        'Info.RegistryExport' = 'レジストリ エクスポート: {0}'
        'Info.SnapshotJson' = 'JSON スナップショット: {0}'
        'Info.ProfileTargetFonts' = '優先フォント: {0}'
        'Info.MatchingSegoeValues' = '一致した "Segoe UI*" 値の数: {0}'
        'Info.ManagedValuesFound' = 'このプロファイルが管理する値の数: {0}'
        'Info.DryRunNoWrite' = 'dry-run モードです。レジストリには書き込みません。'
        'Info.BackupLocation' = 'バックアップ先: {0}'
        'Info.UpdatingValue' = '{0} を更新しています'
        'Info.RegistryPath' = 'レジストリ パス: {0}'
        'Info.LatestValidBackup' = '最新の有効なバックアップ: {0}'
        'Info.TotalSystemLinkValues' = 'SystemLink の値の総数: {0}'
        'Info.SelectedBackup' = '選択されたバックアップ: {0}'
        'Info.CreatedAtUtc' = '作成時刻 (UTC): {0}'
        'Info.ContainsValues' = 'レジストリ値 {0} 個を含みます。'
        'Info.ValueNamesToRestore' = 'これから復元するレジストリ値名:'
        'Info.CurrentStateSafetyBackup' = '現在状態の安全バックアップ: {0}'
        'Info.LanguageSwitched' = 'UI 言語を {0} に切り替えました。'
        'Info.CurrentLanguage' = '現在の UI 言語: {0}'
        'Info.LatestBackupSummaryNone' = 'なし'
        'Success.NoChangesNeeded' = '変更は不要なため、バックアップもレジストリ書き込みも実行しません。'
        'Success.NoOrderingChanges' = 'このプロファイルでは並び替えは不要です。'
        'Success.ApplyVerified' = '{0} 個の管理対象レジストリ値を更新し、検証も完了しました。'
        'Success.RestoreVerified' = 'バックアップ {0} からの復元と検証が正常に完了しました。'
        'Warn.LogoffRequired' = 'FontLink の変更を完全に反映するには、サインアウト、再起動、または対象アプリの再起動が必要な場合があります。'
        'Warn.NoSegoeValuesPreview' = '対象レジストリ キーに "Segoe UI" で始まる値が見つかりません。'
        'Warn.NoManagedValuesPreview' = '対象レジストリ キーに、このプロファイルが管理する値が見つかりません。'
        'Preview.Value' = 'レジストリ値: {0}'
        'Preview.WillChange' = '変更対象: {0}'
        'Preview.Yes' = 'はい'
        'Preview.No' = 'いいえ'
        'Preview.Before' = '変更前:'
        'Preview.After' = '変更後:'
        'Label.Profile' = 'プロファイル: {0}'
        'Label.Name' = '  名前: {0}'
        'Label.Description' = '  説明: {0}'
        'Label.PriorityFonts' = '  優先フォント: {0}'
        'Tui.Welcome' = '単キー操作のメインメニュー'
        'Tui.Option.Backup' = '1. 現在の SystemLink キーをバックアップ'
        'Tui.Option.PreviewApply' = '2. プロファイル変更をプレビュー'
        'Tui.Option.Apply' = '3. プロファイルを適用'
        'Tui.Option.RestoreLatest' = '4. 最新の有効なバックアップを復元'
        'Tui.Option.RestorePath' = '5. 指定したバックアップ パスから復元'
        'Tui.Option.Status' = '6. 現在の状態を表示'
        'Tui.Option.ListProfiles' = '7. 対応プロファイルを表示'
        'Tui.Option.SwitchLanguage' = '8. UI 言語を切り替え'
        'Tui.Option.Help' = '9. コマンド ヘルプを表示'
        'Tui.Option.Exit' = '0. 終了'
        'Tui.Option.Back' = '0. 戻る'
        'Tui.Option.Confirm' = '1. 実行'
        'Tui.Option.Cancel' = '0. キャンセル'
        'Tui.ActionHint' = '数字キー: 開く'
        'Tui.PressAnyKey' = '任意キー: 戻る'
        'Tui.Prompt.SelectOption' = 'メニュー番号を入力してください'
        'Tui.Prompt.SelectProfile' = 'プロファイル ID を入力してください'
        'Tui.Prompt.BackupPath' = 'バックアップ ディレクトリまたは manifest パスを入力してください'
        'Tui.Prompt.SelectLanguage' = '言語 ID を入力してください'
        'Tui.Prompt.PressEnter' = 'Enter キーで続行'
        'Tui.Prompt.ConfirmApply' = '選択したプロファイルを今すぐ適用しますか?'
        'Tui.Prompt.ConfirmRestoreLatest' = '最新の有効なバックアップを今すぐ復元しますか?'
        'Tui.Prompt.ConfirmRestorePath' = '今入力したバックアップ パスから復元しますか?'
        'Tui.LanguagesHeader' = '利用可能な UI 言語:'
        'Tui.Header.SelectProfile' = 'プロファイル選択'
        'Tui.Header.SelectLanguage' = 'UI 言語選択'
        'Tui.Header.Confirm' = '実行確認'
        'Tui.Cancelled' = 'キャンセルしました。'
    };
    'ko-KR' = @{
        'App.Name' = 'SegoeUI-FontLink-Fixer'
        'Usage.Header' = '사용법:'
        'Usage.Profiles' = '지원 프로필:'
        'Usage.Command.Backup' = '.\SegoeLinker.ps1 backup'
        'Usage.Command.Apply' = '.\SegoeLinker.ps1 apply <profile-id> [--dry-run] [--lang <language-id>]'
        'Usage.Command.RestoreLatest' = '.\SegoeLinker.ps1 restore --latest [--lang <language-id>]'
        'Usage.Command.RestoreFile' = '.\SegoeLinker.ps1 restore --file <backup-directory> [--lang <language-id>]'
        'Usage.Command.List' = '.\SegoeLinker.ps1 list [--lang <language-id>]'
        'Usage.Command.Status' = '.\SegoeLinker.ps1 status [--lang <language-id>]'
        'Usage.Command.Tui' = '.\SegoeLinker.ps1 tui [--lang <language-id>]'
        'Usage.Command.Help' = '.\SegoeLinker.ps1 help'
        'Language.Name.en-US' = 'English'
        'Language.Name.zh-CN' = '简体中文'
        'Language.Name.zh-TW' = '繁體中文'
        'Language.Name.ja-JP' = '日本語'
        'Language.Name.ko-KR' = '한국어'
        'Profile.Name.zh-CN' = '중국어 간체'
        'Profile.Name.zh-TW' = '중국어 번체'
        'Profile.Name.ja-JP' = '일본어'
        'Profile.Name.ko-KR' = '한국어'
        'Profile.Description.zh-CN' = 'Microsoft YaHei 계열 글꼴을 더 앞으로 이동합니다.'
        'Profile.Description.zh-TW' = 'Microsoft JhengHei 계열 글꼴을 더 앞으로 이동합니다.'
        'Profile.Description.ja-JP' = 'Yu Gothic UI 및 Meiryo 계열 글꼴을 더 앞으로 이동합니다.'
        'Profile.Description.ko-KR' = 'Malgun Gothic 계열 글꼴을 더 앞으로 이동합니다.'
        'State.Admin' = '관리자'
        'State.StandardUser' = '표준 사용자'
        'State.RunningAsAdmin' = '현재 관리자 권한으로 실행 중입니다.'
        'State.RunningWithoutAdmin' = '현재 관리자 권한 없이 실행 중입니다.'
        'Elevation.NotAdmin' = '권한 상태: 현재 세션은 관리자 권한이 아닙니다.'
        'Elevation.Relaunching' = '레지스트리에 쓰기 전에 관리자 권한으로 명령을 다시 시작합니다.'
        'Error.StartElevated' = '권한 상승된 PowerShell 프로세스를 시작하지 못했습니다.'
        'Error.ApplyMissingProfile' = 'apply 명령에는 zh-CN 또는 ja-JP 같은 프로필 ID가 필요합니다.'
        'Error.UnknownApplyOption' = '알 수 없는 apply 옵션입니다: {0}'
        'Error.LanguageIdRequired' = '--lang 옵션에는 언어 ID가 필요합니다.'
        'Error.RestoreMissingPath' = 'restore --file 옵션에는 백업 디렉터리 경로가 필요합니다.'
        'Error.UnknownRestoreOption' = '알 수 없는 restore 옵션입니다: {0}'
        'Error.UnknownGlobalOption' = '알 수 없는 전역 옵션입니다: {0}'
        'Error.UnknownCommand' = '알 수 없는 명령입니다: {0}'
        'Error.UnsupportedProfile' = '지원하지 않는 프로필 "{0}" 입니다. 지원 프로필: {1}.'
        'Error.RegistryKeyNotFound' = '레지스트리 키를 찾을 수 없습니다: {0}'
        'Error.UnsupportedSnapshotKind' = '스냅샷에 지원하지 않는 레지스트리 값 형식이 있습니다: {0}'
        'Error.NoSegoeValues' = 'SystemLink 키 아래에서 "Segoe UI"로 시작하는 레지스트리 값을 찾지 못했습니다.'
        'Error.NoManagedValues' = 'SystemLink 키 아래에서 이 프로필이 관리하는 레지스트리 값을 찾지 못했습니다.'
        'Error.NonMultiString' = '레지스트리 값 "{0}" 의 형식이 "{1}" 입니다. 이 도구는 MultiString 형식 FontLink 값만 지원합니다.'
        'Error.ApplyVerificationMissing' = '검증 실패: 적용 후 레지스트리 값이 없습니다: {0}'
        'Error.ApplyVerificationMismatch' = '검증 실패: 기록된 값이 예상과 다릅니다: {0}'
        'Error.ApplyVerificationFailed' = '적용 후 검증에 실패했습니다. 이전 상태로 복원하려면 백업 "{0}" 를 사용하세요.'
        'Error.RestoreLatestOrFile' = '--latest 와 --file 은 동시에 사용할 수 없습니다. 하나만 사용하세요.'
        'Error.RestoreSelectorRequired' = 'restore 에서는 --latest 또는 --file <path> 중 하나를 지정해야 합니다.'
        'Error.NoValidBackups' = '{0} 에서 유효한 백업을 찾지 못했습니다.'
        'Error.BackupDirectoryExists' = '기존 백업 디렉터리를 덮어쓰지 않습니다: {0}'
        'Error.BackupManifestNotFound' = '백업 매니페스트를 찾을 수 없습니다: {0}'
        'Error.BackupIncompleteDirectory' = '이 백업 디렉터리는 불완전한 것으로 표시되어 복원에 사용할 수 없습니다: {0}'
        'Error.BackupManifestIncomplete' = '백업 매니페스트가 불완전합니다: {0}'
        'Error.UnsupportedBackupSchema' = '백업 매니페스트 {1} 의 schema 버전 "{0}" 는 지원하지 않습니다.'
        'Error.BackupWrongRegistryKey' = '백업 매니페스트의 대상 레지스트리 키가 일치하지 않습니다: {0}'
        'Error.BackupFileMissing' = '백업 파일이 없습니다: {0}'
        'Error.BackupSnapshotHashMismatch' = '백업 스냅샷 해시가 일치하지 않습니다: {0}'
        'Error.BackupRegHashMismatch' = '백업 reg 내보내기 해시가 일치하지 않습니다: {0}'
        'Error.BackupSnapshotWrongPath' = '백업 스냅샷의 레지스트리 경로가 일치하지 않습니다: {0}'
        'Error.RegistryExportExists' = '기존 레지스트리 내보내기 파일을 덮어쓰지 않습니다: {0}'
        'Error.RegistryExportFailed' = '레지스트리 내보내기에 실패했습니다: {0}'
        'Error.RestoreVerificationFailed' = '복원 후 검증에 실패했습니다. 복원 전 안전 백업은 "{0}" 에 있습니다.'
        'Error.InvalidSelection' = '잘못된 선택입니다. 다시 시도하세요.'
        'Error.InvalidLanguage' = '지원하지 않는 UI 언어 "{0}" 입니다. 지원 언어: {1}.'
        'Error.ChildCommandFailed' = '명령이 종료 코드 {0} 로 종료되었습니다.'
        'Header.Backup' = '백업'
        'Header.Apply' = '변경 적용'
        'Header.Restore' = '복원'
        'Header.Status' = '상태'
        'Header.Profiles' = '지원 프로필'
        'Header.Preview' = '{0} 미리보기'
        'Header.Tui' = '메인 메뉴'
        'Info.ElevationState' = '권한 상태: {0}'
        'Info.BackingUpKey' = '전체 레지스트리 키를 백업하는 중: {0}'
        'Info.BackupCompleted' = '백업 완료: {0}'
        'Info.RegistryExport' = '레지스트리 내보내기: {0}'
        'Info.SnapshotJson' = 'JSON 스냅샷: {0}'
        'Info.ProfileTargetFonts' = '우선 글꼴: {0}'
        'Info.MatchingSegoeValues' = '일치한 "Segoe UI*" 값 수: {0}'
        'Info.ManagedValuesFound' = '이 프로필이 관리하는 값 수: {0}'
        'Info.DryRunNoWrite' = 'dry-run 모드입니다. 레지스트리에 쓰지 않습니다.'
        'Info.BackupLocation' = '백업 위치: {0}'
        'Info.UpdatingValue' = '{0} 업데이트 중'
        'Info.RegistryPath' = '레지스트리 경로: {0}'
        'Info.LatestValidBackup' = '가장 최근의 유효한 백업: {0}'
        'Info.TotalSystemLinkValues' = 'SystemLink 값 총수: {0}'
        'Info.SelectedBackup' = '선택한 백업: {0}'
        'Info.CreatedAtUtc' = '생성 시각 (UTC): {0}'
        'Info.ContainsValues' = '레지스트리 값 {0}개를 포함합니다.'
        'Info.ValueNamesToRestore' = '복원할 레지스트리 값 이름:'
        'Info.CurrentStateSafetyBackup' = '현재 상태 안전 백업: {0}'
        'Info.LanguageSwitched' = 'UI 언어를 {0}(으)로 전환했습니다.'
        'Info.CurrentLanguage' = '현재 UI 언어: {0}'
        'Info.LatestBackupSummaryNone' = '없음'
        'Success.NoChangesNeeded' = '변경이 필요하지 않으므로 백업도 레지스트리 쓰기도 수행하지 않습니다.'
        'Success.NoOrderingChanges' = '이 프로필에서는 순서 변경이 필요하지 않습니다.'
        'Success.ApplyVerified' = '관리 대상 레지스트리 값 {0}개를 업데이트하고 검증까지 완료했습니다.'
        'Success.RestoreVerified' = '백업 {0} 에서 복원하고 검증까지 성공했습니다.'
        'Warn.LogoffRequired' = 'FontLink 변경 사항이 완전히 반영되려면 로그오프, 재부팅 또는 관련 앱 재시작이 필요할 수 있습니다.'
        'Warn.NoSegoeValuesPreview' = '대상 레지스트리 키 아래에서 "Segoe UI"로 시작하는 값을 찾지 못했습니다.'
        'Warn.NoManagedValuesPreview' = '대상 레지스트리 키 아래에서 이 프로필이 관리하는 값을 찾지 못했습니다.'
        'Preview.Value' = '레지스트리 값: {0}'
        'Preview.WillChange' = '변경 여부: {0}'
        'Preview.Yes' = '예'
        'Preview.No' = '아니요'
        'Preview.Before' = '변경 전:'
        'Preview.After' = '변경 후:'
        'Label.Profile' = '프로필: {0}'
        'Label.Name' = '  이름: {0}'
        'Label.Description' = '  설명: {0}'
        'Label.PriorityFonts' = '  우선 글꼴: {0}'
        'Tui.Welcome' = '단일 키 메인 메뉴'
        'Tui.Option.Backup' = '1. 현재 SystemLink 키 백업'
        'Tui.Option.PreviewApply' = '2. 프로필 변경 미리보기'
        'Tui.Option.Apply' = '3. 프로필 적용'
        'Tui.Option.RestoreLatest' = '4. 가장 최근의 유효한 백업 복원'
        'Tui.Option.RestorePath' = '5. 특정 백업 경로에서 복원'
        'Tui.Option.Status' = '6. 현재 상태 보기'
        'Tui.Option.ListProfiles' = '7. 지원 프로필 보기'
        'Tui.Option.SwitchLanguage' = '8. UI 언어 변경'
        'Tui.Option.Help' = '9. 명령 도움말 보기'
        'Tui.Option.Exit' = '0. 종료'
        'Tui.Option.Back' = '0. 뒤로'
        'Tui.Option.Confirm' = '1. 실행'
        'Tui.Option.Cancel' = '0. 취소'
        'Tui.ActionHint' = '숫자 키: 열기'
        'Tui.PressAnyKey' = '아무 키: 돌아가기'
        'Tui.Prompt.SelectOption' = '메뉴 번호를 입력하세요'
        'Tui.Prompt.SelectProfile' = '프로필 ID를 입력하세요'
        'Tui.Prompt.BackupPath' = '백업 디렉터리 또는 manifest 경로를 입력하세요'
        'Tui.Prompt.SelectLanguage' = '언어 ID를 입력하세요'
        'Tui.Prompt.PressEnter' = '계속하려면 Enter 키를 누르세요'
        'Tui.Prompt.ConfirmApply' = '선택한 프로필을 지금 적용하시겠습니까?'
        'Tui.Prompt.ConfirmRestoreLatest' = '가장 최근의 유효한 백업을 지금 복원하시겠습니까?'
        'Tui.Prompt.ConfirmRestorePath' = '방금 입력한 백업 경로에서 복원하시겠습니까?'
        'Tui.LanguagesHeader' = '사용 가능한 UI 언어:'
        'Tui.Header.SelectProfile' = '프로필 선택'
        'Tui.Header.SelectLanguage' = 'UI 언어 선택'
        'Tui.Header.Confirm' = '실행 확인'
        'Tui.Cancelled' = '취소했습니다.'
    }
}

$script:SupportedLanguages = @(
    [pscustomobject]@{ Id = 'en-US'; NativeName = 'English' }
    [pscustomobject]@{ Id = 'zh-CN'; NativeName = '简体中文' }
    [pscustomobject]@{ Id = 'zh-TW'; NativeName = '繁體中文' }
    [pscustomobject]@{ Id = 'ja-JP'; NativeName = '日本語' }
    [pscustomobject]@{ Id = 'ko-KR'; NativeName = '한국어' }
)

$script:UiLanguage = $script:DefaultUiLanguage

function Get-SupportedLanguages {
    return $script:SupportedLanguages
}

function Resolve-Language {
    param(
        [Parameter(Mandatory = $true)]
        [string]$LanguageId
    )

    $match = $script:SupportedLanguages | Where-Object { $_.Id -ieq $LanguageId } | Select-Object -First 1
    if ($null -eq $match) {
        $supportedList = ($script:SupportedLanguages | ForEach-Object { $_.Id }) -join ', '
        throw (Format-LocalizedString -Key 'Error.InvalidLanguage' -Arguments @($LanguageId, $supportedList))
    }

    return $match
}

function Set-UiLanguage {
    param(
        [Parameter(Mandatory = $true)]
        [string]$LanguageId
    )

    $language = Resolve-Language -LanguageId $LanguageId
    $script:UiLanguage = $language.Id
    return $language
}

function Get-UiLanguage {
    return $script:UiLanguage
}

function Get-LocalizedString {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Key
    )

    $language = if ($script:LocalizationCatalog.ContainsKey($script:UiLanguage)) { $script:UiLanguage } else { $script:DefaultUiLanguage }
    $languageCatalog = $script:LocalizationCatalog[$language]
    if ($languageCatalog.ContainsKey($Key)) {
        return $languageCatalog[$Key]
    }

    $fallbackCatalog = $script:LocalizationCatalog[$script:DefaultUiLanguage]
    if ($fallbackCatalog.ContainsKey($Key)) {
        return $fallbackCatalog[$Key]
    }

    return $Key
}

function Format-LocalizedString {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Key,

        [object[]]$Arguments = @()
    )

    $template = Get-LocalizedString -Key $Key
    if ($null -eq $Arguments -or $Arguments.Count -eq 0) {
        return $template
    }

    return ($template -f $Arguments)
}

function Get-LocalizedLanguageName {
    param(
        [Parameter(Mandatory = $true)]
        [string]$LanguageId
    )

    return (Get-LocalizedString -Key ('Language.Name.{0}' -f $LanguageId))
}

function Get-ProfileDisplayName {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ProfileId
    )

    return (Get-LocalizedString -Key ('Profile.Name.{0}' -f $ProfileId))
}

function Get-ProfileDescription {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ProfileId
    )

    return (Get-LocalizedString -Key ('Profile.Description.{0}' -f $ProfileId))
}
